apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-a
  template:
    metadata:
      labels:
        app: client-a
    spec:
      containers:
        - name: client-a
          image: client:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              value: "cluster-leilao"
            - name: EXCHANGE_NAME
              value: "leilao.events"
            - name: CLIENT_ID
              value: "client_a"
            - name: BID_INTERVAL
              value: "8"
            - name: PRIVATE_KEY_PATH
              value: "/app/src/private-keys/privatea.pem"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster-leilao-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-leilao-default-user
                  key: password
            - name: RABBITMQ_PORT
              value: "5672"
          args: ["python", "src/clients/client.py"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-b
  template:
    metadata:
      labels:
        app: client-b
    spec:
      containers:
        - name: client-b
          image: client:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              value: "cluster-leilao"
            - name: EXCHANGE_NAME
              value: "leilao.events"
            - name: CLIENT_ID
              value: "client_b"
            - name: BID_INTERVAL
              value: "11"
            - name: PRIVATE_KEY_PATH
              value: "/app/src/private-keys/privateb.pem"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster-leilao-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-leilao-default-user
                  key: password
            - name: RABBITMQ_PORT
              value: "5672"
          args: ["python", "src/clients/client.py"]
